# Generated by Django 2.1.1 on 2018-11-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fkey', '0002_salary_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='SEX',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
