# Generated by Django 2.1.1 on 2018-11-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fkey', '0003_employee_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='NAME',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
