# Generated by Django 2.1.1 on 2018-11-06 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_contact'),
        ('fkey', '0004_auto_20181106_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='CONTACT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.contact'),
        ),
    ]
