# Generated by Django 2.1.1 on 2018-11-07 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADDR', models.TextField(null=True)),
                ('NUM', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=255, unique=True)),
                ('SEX', models.CharField(max_length=10)),
                ('CONTACT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='tables.contact')),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('LEVEL', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('SALARY', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='LEVEL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='tables.level'),
        ),
    ]
