# Generated by Django 2.1.1 on 2018-11-07 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20181107_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='CONTACT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.contact'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='LEVEL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.level'),
        ),
    ]
