# Generated by Django 2.1.1 on 2018-11-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADDR', models.TextField(null=True)),
                ('NUM', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
