# Generated by Django 2.1.1 on 2018-11-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=255)),
                ('EMAIL', models.EmailField(max_length=254)),
            ],
        ),
    ]
